import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import { getAuth, setPersistence, browserSessionPersistence, signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import * as store from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=store.initializeFirestore(app,{localCache:store.memoryLocalCache()}),$=s=>document.querySelector(s);
let profileStop,controlStop,started=false,handling=false;
const message=e=>({'auth/invalid-credential':'E-Mail-Adresse oder Passwort ist nicht korrekt.','auth/invalid-email':'Bitte eine gültige E-Mail-Adresse eingeben.','auth/user-disabled':'Dieser Zugang wurde deaktiviert.','auth/too-many-requests':'Zu viele Anmeldeversuche. Bitte später erneut versuchen.','auth/network-request-failed':'Keine Verbindung zum Anmeldedienst. Bitte die Internetverbindung prüfen.'}[e.code]||KPStorage.error(e).message);
function loading(text,on=true){$('#loading-text').textContent=text;$('#loading').hidden=!on;}
function alertLogin(text){$('#login-error').textContent=text;$('#login').hidden=false;$('#shell').hidden=true;}
function script(file){return new Promise((resolve,reject)=>{const x=document.createElement('script');x.src='js/'+file+'.js';x.onload=resolve;x.onerror=()=>reject(Error('Programmdatei konnte nicht geladen werden. Bitte die Seite neu laden.'));document.body.appendChild(x);});}
async function start(state){const rt=await KPStorage.runtimeData();globalThis.KP_SOURCE=rt.source;globalThis.KP_ARCHIVE=rt.archive||[];if(!started){for(const f of ['engine','domain','matrix','app'])await script(f);started=true;}$('#cloud-setup').hidden=true;$('#login').hidden=true;$('#shell').hidden=false;$('#password').value='';const label=document.querySelector('.username');label.textContent=KPSession.email+' · '+(KPSession.role==='admin'?'Administrator':'Benutzer');document.querySelector('.avatar').textContent=KPSession.email.slice(0,2).toUpperCase();KPUI.start(state);if(controlStop)controlStop();let first=true;controlStop=store.onSnapshot(store.doc(db,'system','control'),snap=>{if(first){first=false;return;}if(snap.exists()){const n=$('#cloud-notice');n.textContent='Ein neuer Cloud-Datenbestand ist verfügbar. Bitte Cloud-Daten neu laden.';n.hidden=false;}},e=>{console.error('Cloud status',e);const n=$('#cloud-notice');n.textContent=message(e);n.hidden=false;});}
await setPersistence(auth,browserSessionPersistence);
globalThis.KPSession={uid:null,email:'',role:null};
globalThis.KPAuth={logout:async()=>{await signOut(auth);location.reload();},message};
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-error').textContent='';const button=$('#login-form button');button.disabled=true;try{await signInWithEmailAndPassword(auth,$('#email').value.trim(),$('#password').value);}catch(e){alertLogin(message(e));}finally{button.disabled=false;}});
onAuthStateChanged(auth,async user=>{if(handling)return;if(profileStop){profileStop();profileStop=null;}if(controlStop){controlStop();controlStop=null;}if(!user){KPStorage.clear();globalThis.KP_SOURCE=null;globalThis.KP_ARCHIVE=[];if(started){location.reload();return;}$('#cloud-setup').hidden=true;$('#login').hidden=false;$('#shell').hidden=true;return;}handling=true;loading('Berechtigung und geschützte Cloud-Daten werden geladen …');try{const p=await store.getDocFromServer(store.doc(db,'users',user.uid));const role=p.data();if(!p.exists()||role.active!==true||!['admin','user'].includes(role.role))throw Error('Für diesen Zugang ist keine aktive KalkPro-Berechtigung hinterlegt. Bitte den Administrator kontaktieren.');globalThis.KPSession={uid:user.uid,email:user.email||role.email,role:role.role};KPStorage.init(store,db,KPSession);profileStop=store.onSnapshot(store.doc(db,'users',user.uid),snap=>{if(!snap.exists()||snap.data().active!==true||snap.data().role!==KPSession.role)KPAuth.logout();},()=>KPAuth.logout());const state=await KPStorage.read();if(state)await start(state);else if(role.role==='admin'){$('#login').hidden=true;$('#cloud-setup').hidden=false;}else throw Error('Die Cloud-Daten wurden noch nicht eingerichtet. Bitte den Administrator kontaktieren.');}catch(e){console.error('KalkPro initialization',e);alertLogin(message(e));KPStorage.clear();globalThis.KP_SOURCE=null;globalThis.KP_ARCHIVE=[];await signOut(auth);}finally{handling=false;loading('',false);}});
$('#setup-import').addEventListener('click',async()=>{const file=$('#setup-file').files[0];if(!file){$('#setup-error').textContent='Bitte das private Ausgangsdaten-JSON auswählen.';return;}if(!confirm('Geschützte Ausgangsdaten jetzt in das neue KalkPro-TGA-Firestore-Projekt importieren?'))return;loading('Ausgangsdaten werden geschützt importiert …');try{if(file.size>100*1024*1024)throw Error('Die Datei ist größer als 100 MB.');const input=JSON.parse(await file.text(),(k,v)=>{if(['__proto__','prototype','constructor'].includes(k))throw Error('Unzulässiger Inhalt.');return v;});if(input.format!=='KalkPro-TGA-Initialdaten'||!input.runtime||!input.state)throw Error('Bitte das mitgelieferte private Ausgangsdatenpaket verwenden.');await start(await KPStorage.restore(input.state,input.runtime));}catch(e){console.error('Initial import',e);$('#setup-error').textContent=message(e);}finally{loading('',false);}});
$('#setup-logout').addEventListener('click',()=>KPAuth.logout());
