/* Jede Zelle ist ein Musterprojekt im bestehenden Rechenkern. */
(function(root){'use strict';const D=root.KPDomain,{B,P,C}=D,clone=D.clone;
const distances=Array.from({length:20},(_,i)=>(i+1)*10),quantities=Array.from({length:10},(_,i)=>(i+1)*10);
function definitions(){const roofs=['Stockschrauben','Schrägdach','Trapezblech','Flachdach Ost/West','Flachdach Süd'].map((label,i)=>({id:'pv-'+i,label,roof:'DEFGH'[i]})),ac=[];for(const [group,row,labelRow,scope,end] of [['Hybrid-Wechselrichter',34,33,'K19','P'],['Strang-Wechselrichter',37,36,'K19','P'],['Speicher',45,44,'L19','J'],['Zählerschrank',52,51,'M19','N'],['Wärmepumpe',57,56,'N19','N'],['Wallbox',62,61,'O19','N']])for(const c of root.KPEngine.range('C1',end+'1').map(x=>x.slice(0,-1))){const label=root.KP_SOURCE.sheets[P][c+labelRow]?.v;if(label&&label!=='./.'&&!String(label).startsWith('='))ac.push({id:'ac-'+c+row,label:group+' · '+label,cell:c+row,scope});}return {roofs,ac};}
function basis(price,parameters){return {model:13,source:root.KP_SOURCE.sourceSha256,priceId:price.id,priceName:price.name,priceDate:price.date,parameterId:parameters.id,parameterDate:parameters.date,parameters:clone(parameters.overrides),priceOverrides:clone(price.overrides),pdsCatalog:clone(price.pdsCatalog||null)};}
function fingerprint(b){return JSON.stringify(b,function(k,v){return v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.keys(v).sort().map(k=>[k,v[k]])):v;});}
function valid(a){if(!Number.isSafeInteger(a.people)||a.people<1||!Number.isSafeInteger(a.vehicles)||a.vehicles<1)throw Error('Personen und Fahrzeuge müssen positive ganze Zahlen sein.');return clone(a);}
function rowAssumptions(matrix,row){return clone(row.assumptions||row.cells?.[0]?.assumptions||(row.cells?.[0]?.details?{people:row.cells[0].details.people,vehicles:row.cells[0].details.vehicles}:matrix.assumptions));}
function planning(matrix){return {ac:clone(matrix.assumptions),pv:Object.fromEntries(matrix.pv.map(def=>[def.id,Object.fromEntries(def.rows.map(row=>[row.quantity,rowAssumptions(matrix,row)]))]))};}
function average(b){const e=new root.KPEngine.Engine(root.KP_SOURCE.sheets,b.parameters),values=['B10','D10','C10','E10'].map(c=>Number(e.safe(B,c)));if(values.some(x=>!Number.isFinite(x)||x<0))throw Error('Ungültige Stundensätze.');return values.reduce((a,x)=>a+x,0)/4;}
function project(b,def,qty,km,a){const pin={};for(const [c,x]of Object.entries(root.KP_SOURCE.sheets[P]))if(!x.f)pin[c]=typeof x.v==='boolean'?false:typeof x.v==='number'?0:x.v;Object.assign(pin,{C9:false,D9:true,G9:true,M14:km,M15:km,I9:0,L9:0,O9:0,I10:false,C82:1,E82:1,C86:a.people,D86:0,E86:0,F86:0,G86:0,H86:a.vehicles,I86:1,H14:'Musterprojekt'});if(def.roof){pin.J19=true;pin.C19=qty;pin[def.roof+'19']=true;}else{pin[def.scope]=true;pin[def.cell]=true;}
const parameters=clone(b.parameters);parameters[B]??={};const mean=average(b);for(const c of ['B10','C10','D10','E10'])parameters[B][c]=mean;parameters[B].B20=false;
const p={pricingModel:13,customer:'Preismatrix',title:def.label,parameters,priceOverrides:clone(b.priceOverrides),pdsCatalog:clone(b.pdsCatalog),inputs:{[P]:pin},catalogServices:[],supplements:[],pvExtraEffort:false},preview=D.planningPreview(p),capacity=a.people*(8-preview.roundTripHours);if(!(capacity>0))throw Error('Fahrtzeit lässt bei '+km+' km keine Montage innerhalb eines 8-h-Tages zu. Fahrtgeschwindigkeit prüfen.');pin.I86=Math.max(1,Math.ceil(preview.montageHours/capacity));return p;}
// Details contain saved results, never an independent price calculation.
function storedDetails(matrix,cell,quantity,distance){const m=cell.metrics;if(!m||!Number.isFinite(cell.total))throw Error('Gespeicherte Berechnungsdetails fehlen.');const parameter=c=>Number(matrix.basis.parameters?.[B]?.[c]??root.KP_SOURCE.sheets[B][c]?.v??0),people=Number((cell.assumptions||matrix.assumptions).people),days=Number(cell.days),roundTripHours=people*days>0?m.travelHours/(people*days):0;
 return {schema:1,average:matrix.average,quantity,distance,people,vehicles:(cell.assumptions||matrix.assumptions).vehicles,days,roundTripHours,speed:roundTripHours>0?distance*2/roundTripHours:parameter('I19'),vehicleRate:m.kilometers?m.vehicle/m.kilometers:parameter('H19'),overheadRate:m.material?m.overhead/m.material*100:parameter('I10'),profitRate:m.selfCost?m.profit/m.selfCost*100:parameter('H10'),commissionRate:m.plannedDiscount,skontoRate:m.plannedSkonto,material:m.material,montageHours:m.montageHours,montagePersonnel:m.montagePersonnel,travelHours:m.travelHours,travelPersonnel:m.travelPersonnel,vehicle:m.vehicle,kilometers:m.kilometers,travelOther:m.travelOther,bonus:m.bonus,otherDirect:Number(m.supplementPlannedCost||0),overhead:m.overhead,selfCost:m.selfCost,profit:m.profit,barRevenue:m.revenue,commission:m.plannedDiscountAmount,skonto:m.plannedSkontoAmount,total:cell.total};
}
function cellDetails(matrix,cell,quantity,distance){const d=cell.details||storedDetails(matrix,cell,quantity,distance);if(d.total!==cell.total)throw Error('Gespeicherter Detailpreis passt nicht zum Matrixwert.');return clone(d);}
function hydrateDetails(matrix){if(!matrix)return false;let changed=false;for(const def of matrix.pv||[])for(const row of def.rows||[])for(const [i,cell]of row.cells.entries())if(!cell.details){cell.details=storedDetails(matrix,cell,row.quantity,distances[i]);changed=true;}for(const def of matrix.ac||[])for(const [i,cell]of def.cells.entries())if(!cell.details){cell.details=storedDetails(matrix,cell,null,distances[i]);changed=true;}if(changed)matrix.detailsSchema=1;return changed;}
function calculateCell(out,def,q,km,a){valid(a);const p=project(out.basis,def,q,km,a),c=D.calculation(p);if(!c.metrics)throw Error(def.label+' / '+q+' / '+km+' km: '+c.issues.join(', '));const cell={total:c.metrics.invoice,metrics:clone(c.metrics),days:p.inputs[P].I86,assumptions:clone(a)};cell.details=storedDetails(out,cell,def.roof?q:null,km);cell.details.overheadRate=Number(c.engine.safe(B,'I10'));cell.details.profitRate=Number(c.engine.safe(B,'H10'));cell.details.vehicleRate=Number(c.engine.safe(B,'H19'));cell.details.speed=Number(c.engine.safe(B,'I19'));cell.details.profit=Number(c.engine.safe(C,'D183'));return cell;}
function recalculatePVRow(matrix,roofId,quantity,a){valid(a);const out=clone(matrix),def=out.pv.find(x=>x.id===roofId),row=def?.rows.find(x=>x.quantity===quantity);if(!row)throw Error('Modulzeile nicht gefunden.');row.cells=distances.map(km=>calculateCell(out,def,quantity,km,a));row.assumptions=clone(a);return out;}
async function recalculateAC(matrix,a){valid(a);const out=clone(matrix);out.assumptions=clone(a);for(const def of out.ac){def.cells=distances.map(km=>calculateCell(out,def,1,km,a));await new Promise(r=>setTimeout(r,0));}return out;}
async function generate(b,a={people:2,vehicles:1},progress=()=>{}){const ac=valid(a.ac||a),defs=definitions(),out={id:root.crypto?.randomUUID?.()||Date.now().toString(),created:new Date().toISOString(),detailsSchema:1,basis:clone(b),fingerprint:fingerprint(b),average:average(b),assumptions:ac,remark:'',pv:[],ac:[]};let count=0;
for(const def of defs.roofs){const rows=[];for(const q of quantities){const team=valid(a.pv?.[def.id]?.[q]||ac);rows.push({quantity:q,assumptions:team,cells:distances.map(km=>calculateCell(out,def,q,km,team))});count+=20;progress(count);await new Promise(r=>setTimeout(r,0));}out.pv.push({...def,rows});}
for(const def of defs.ac){out.ac.push({...def,cells:distances.map(km=>calculateCell(out,def,1,km,ac))});count+=20;progress(count);await new Promise(r=>setTimeout(r,0));}return out;}
function archive(next,current){next.matrixHistory??=[];if(current&&!next.matrixHistory.some(x=>x.id===current.id))next.matrixHistory.push(clone({...current,savedAt:new Date().toISOString()}));}
root.KPMatrix={valid,rowAssumptions,planning,recalculatePVRow,recalculateAC,distances,quantities,definitions,basis,fingerprint,average,project,generate,archive,storedDetails,cellDetails,hydrateDetails};})(globalThis);
