/* Firestore entity adapter. The SDK is injected by firebase.js. */
(function(root){'use strict';
const M=KPCloudModel;let api,db,session,generation,controlRevision=0,runtime,baseline,headers=new Map(),blobCache=new Map(),writing=false;
const uid=()=>session.uid,admin=()=>session.role==='admin',ref=(kind,id)=>api.doc(db,'datasets',generation,kind,id),control=()=>api.doc(db,'system','control');
function needAdmin(){if(!admin())throw Error('Diese Funktion ist Administratoren vorbehalten.');}
function error(e){console.error('KalkPro Firestore operation failed',e);if(e.message&&(!e.code||e.code==='conflict'))return e;const messages={'permission-denied':'Keine Berechtigung. Bitte die Rolle bzw. den Projektstatus prüfen und aktuelle Daten neu laden.','unauthenticated':'Die Anmeldung ist abgelaufen. Bitte erneut anmelden.','unavailable':'Keine Verbindung zu Firestore. Bitte die Internetverbindung prüfen.','deadline-exceeded':'Firestore hat nicht rechtzeitig geantwortet. Bitte erneut versuchen.','resource-exhausted':'Das Firestore-Kontingent ist ausgeschöpft. Bitte den Administrator informieren.'};return Error(messages[e.code]||'Cloud-Zugriff fehlgeschlagen. Bitte erneut versuchen.');}
function conflict(){const e=Error('Der Datenstand wurde inzwischen geändert. Bitte „Cloud-Daten neu laden“ wählen. Ungespeicherte Eingaben vorher separat sichern.');e.code='conflict';return e;}
function init(sdk,database,identity){api=sdk;db=database;session=identity;clear();}
function clear(){headers.clear();blobCache.clear();baseline=null;runtime=null;generation=null;controlRevision=0;}
async function getControl(){const s=await api.getDocFromServer(control());if(!s.exists())return null;const c=s.data();generation=c.generation;controlRevision=c.revision;return c;}
async function loadBlob(id){if(!id)return null;if(blobCache.has(id))return M.clone(blobCache.get(id));const h=await api.getDocFromServer(ref('blobs',id));if(!h.exists()||!h.data().sealed)throw Error('Unvollständiger Cloud-Datensatz.');const head=h.data(),parts=await api.getDocsFromServer(api.collection(ref('blobs',id),'parts'));if(parts.size!==head.count)throw Error('Ein Cloud-Datensatz ist unvollständig.');const arr=[];parts.forEach(x=>arr[Number(x.id)]=x.data().text);const txt=arr.join('');if(await M.hash(txt)!==head.hash)throw Error('Die Integritätsprüfung eines Cloud-Datensatzes ist fehlgeschlagen.');const value=JSON.parse(txt,(k,v)=>{if(['__proto__','prototype','constructor'].includes(k))throw Error('Unzulässiger Datensatz.');return v;});blobCache.set(id,value);return M.clone(value);}
async function stage(kind,entityId,value){if(value===null)return null;const text=M.canonical(value),hash=await M.hash(text),id=crypto.randomUUID(),pieces=M.chunks(text);if(pieces.length>2000)throw Error('Dieser einzelne Datensatz ist zu groß (über 96 Millionen Zeichen).');const h=ref('blobs',id);await api.setDoc(h,{kind,entityId,hash,count:pieces.length,sealed:false,createdBy:uid(),createdAt:api.serverTimestamp()});for(let i=0;i<pieces.length;i+=40){const b=api.writeBatch(db);pieces.slice(i,i+40).forEach((text,j)=>b.set(api.doc(h,'parts',String(i+j)),{text}));await b.commit();}await api.updateDoc(h,{sealed:true});blobCache.set(id,M.clone(value));return id;}
async function list(kind){const docs=await api.getDocsFromServer(api.collection(db,'datasets',generation,kind)),out=[];docs.forEach(x=>{const h={...x.data(),id:x.id};headers.set(kind+'/'+x.id,h);out.push(h);});return out;}
async function read(){try{const c=await getControl();if(!c)return null;baseline=null;headers.clear();const [settingsDoc,runtimeDoc,prices,params,projects,matrices]=await Promise.all([api.getDocFromServer(ref('settings','main')),api.getDocFromServer(ref('runtime','main')),list('prices'),list('parameters'),list('projects'),list('matrices')]);if(!settingsDoc.exists()||!runtimeDoc.exists())throw Error('Die Cloud-Einrichtung ist unvollständig.');const settings=settingsDoc.data();headers.set('settings/main',settings);runtime=await loadBlob(runtimeDoc.data().blob);const s={format:'KalkPro-TGA',schema:1,sourceHash:runtime.source.sourceSha256,projects:[],priceVersions:[],parameterVersions:[],matrixHistory:[],activePrice:settings.activePrice,activeParameters:settings.activeParameters,lastNumber:0};
// Limit simultaneous chunk downloads, and reuse immutable blobs within the session.
for(const h of prices)s.priceVersions.push(await loadBlob(h.blob));for(const h of params)s.parameterVersions.push(await loadBlob(h.blob));for(const h of projects){const [p,a,m,planned]=await Promise.all([loadBlob(h.plan),loadBlob(h.actual),loadBlob(h.meta),loadBlob(h.planned)]);s.projects.push(M.joinProject(h,p,a,m,planned,s));}for(const h of matrices){const m=await loadBlob(h.blob);if(h.id==='current')s.matrixCurrent=m;else s.matrixHistory.push(m);}s.matrixHistory.sort((a,b)=>String(a.created).localeCompare(String(b.created)));const count=await api.getDocFromServer(ref('counters','projects'));s.lastNumber=count.exists()?count.data().value:0;const [lastControl,lastSettings]=await Promise.all([api.getDocFromServer(control()),api.getDocFromServer(ref('settings','main'))]);if(lastControl.data()?.generation!==generation||lastControl.data()?.revision!==controlRevision||lastSettings.data()?.revision!==settings.revision)throw conflict();baseline=M.clone(s);return s;}catch(e){throw error(e);}}
async function runtimeData(){if(!runtime)throw Error('Geschützte Ausgangsdaten wurden noch nicht geladen.');return M.clone(runtime);}
function meta(old){return {revision:(old?.revision||0)+1,createdAt:old?.createdAt||api.serverTimestamp(),createdBy:old?.createdBy||uid(),updatedAt:api.serverTimestamp(),updatedBy:uid()};}
async function reserveNumber(){try{return await api.runTransaction(db,async t=>{const [c,n]=await Promise.all([t.get(control()),t.get(ref('counters','projects'))]);if(c.data()?.generation!==generation)throw conflict();const value=(n.exists()?n.data().value:0)+1;t.set(ref('counters','projects'),{value,updatedAt:api.serverTimestamp(),updatedBy:uid()});if(baseline)baseline.lastNumber=value;return value;});}catch(e){throw error(e);}}
async function removeEntityBlobs(kind,entityId){const q=api.query(api.collection(db,'datasets',generation,'blobs'),api.where('entityId','==',entityId));const all=await api.getDocsFromServer(q);for(const h of all.docs){const data=h.data();if(kind==='projects'&&!['plan','actual','meta'].includes(data.kind)||kind==='matrices'&&data.kind!=='matrices')continue;const parts=await api.getDocsFromServer(api.collection(h.ref,'parts'));for(let i=0;i<parts.docs.length;i+=150){const batch=api.writeBatch(db);parts.docs.slice(i,i+150).forEach(p=>batch.delete(p.ref));await batch.commit();}await api.deleteDoc(h.ref);blobCache.delete(h.id);}}
async function changedBlob(kind,id,value,oldRef,oldValue){return M.equal(value,oldValue)?oldRef||null:stage(kind,id,value);}
async function write(next){if(writing)throw Error('Ein Speichervorgang läuft bereits. Bitte kurz warten.');writing=true;root.KPStorage.deletionWarning='';try{if(!baseline)throw Error('Bitte die Cloud-Daten zuerst laden.');M.validateState(next,baseline.sourceHash);if(admin()){for(const p of next.projects){const version=next.parameterVersions.find(v=>v.id===p.parameterVersion);if(p.parameters&&(!version||!M.equal(version.overrides||{},p.parameters))){const id='project-'+(await M.hash(M.canonical(p.parameters))).slice(0,32);if(!next.parameterVersions.some(v=>v.id===id))next.parameterVersions.push({id,date:new Date().toISOString(),user:session.email,overrides:M.clone(p.parameters)});p.parameterVersion=id;}}}const changes=[];const add=(kind,id,data)=>changes.push({kind,id,data,old:headers.get(kind+'/'+id)});
for(const [kind,key]of [['prices','priceVersions'],['parameters','parameterVersions']]){for(const v of next[key]){const old=baseline[key].find(x=>x.id===v.id);if(M.equal(v,old))continue;needAdmin();if(old)throw Error('Historische Preis- und Parameterstände dürfen nicht verändert werden.');add(kind,v.id,{blob:await stage(kind,v.id,v)});}if(baseline[key].some(x=>!next[key].some(y=>y.id===x.id)))throw Error('Preis- und Parameterhistorie kann nur durch eine bestätigte Wiederherstellung ersetzt werden.');}
if(next.activePrice!==baseline.activePrice||next.activeParameters!==baseline.activeParameters){needAdmin();add('settings','main',{activePrice:next.activePrice,activeParameters:next.activeParameters});}
for(const p of next.projects){const old=baseline.projects.find(x=>x.id===p.id);if(M.equal(p,old))continue;const h=headers.get('projects/'+p.id),sp=M.splitProject(p),so=old?M.splitProject(old):null;
if(!admin()&&!M.equal(p.parameters,next.parameterVersions.find(x=>x.id===p.parameterVersion)?.overrides||{}))throw Error('Globale Parameter können nur Administratoren ändern.');
if(so?.status==='Abgeschlossen')throw Error('Das abgeschlossene Projekt ist schreibgeschützt.');
if(old?.actual?.status==='Abgeschlossen'&&!M.equal(sp.actual,so.actual))throw Error('Die abgeschlossene Nachkalkulation ist schreibgeschützt.');
if(so?.protected&&!M.equal(sp.plan,so.plan))throw Error('Speicherschutz ist aktiv. Bitte zuerst aufheben.');
if(so&&(so.status!=='Entwurf'||so.protected)&&sp.status!=='Entwurf'&&(sp.parameterId!==so.parameterId||sp.priceId!==so.priceId))throw Error('Der eingefrorene Preis- und Parameterstand darf nicht verändert werden.');
const plan=await changedBlob('plan',p.id,sp.plan,h?.plan,so?.plan),actual=await changedBlob('actual',p.id,sp.actual,h?.actual,so?.actual),m=await changedBlob('meta',p.id,sp.meta,h?.meta,so?.meta);let planned=h?.planned||null,plannedParameterId=h?.plannedParameterId||'',plannedPriceId=h?.plannedPriceId||'';
if(sp.actual&&!planned){planned=plan;plannedParameterId=sp.parameterId;plannedPriceId=sp.priceId;}
add('projects',p.id,{plan,actual,meta:m,planned,plannedParameterId,plannedPriceId,parameterId:sp.parameterId,priceId:sp.priceId,status:sp.status,protected:sp.protected,locked:sp.locked,actualClosed:sp.actual?.status==='Abgeschlossen',numberKey:await M.hash(M.numberKey(p.number))});}
for(const p of baseline.projects)if(!next.projects.some(x=>x.id===p.id)){needAdmin();add('projects',p.id,null);}
for(const [id,m]of [['current',next.matrixCurrent],...(next.matrixHistory||[]).map(m=>[m.id,m])]){const old=id==='current'?baseline.matrixCurrent:baseline.matrixHistory.find(x=>x.id===id);if(M.equal(m,old))continue;needAdmin();if(id!=='current'&&old)throw Error('Historische Matrixstände dürfen nicht verändert werden.');if(m)add('matrices',id,{blob:await stage('matrices',id,m)});}
for(const m of baseline.matrixHistory||[])if(!(next.matrixHistory||[]).some(x=>x.id===m.id)){needAdmin();add('matrices',m.id,null);}
if(changes.length>8)throw Error('Zu viele Änderungen gleichzeitig. Bitte einzelne Vorgänge speichern; große Sicherungen über „Wiederherstellen“ importieren.');
if(changes.length){await api.runTransaction(db,async t=>{const ctrl=await t.get(control());if(ctrl.data()?.generation!==generation||ctrl.data()?.revision!==controlRevision)throw conflict();const settings=await t.get(ref('settings','main'));if(changes.some(x=>x.kind==='projects'&&x.data&&x.data.status==='Entwurf'&&!x.data.protected)&&settings.data()?.revision!==headers.get('settings/main')?.revision)throw conflict();for(const x of changes.filter(x=>x.kind==='projects'&&x.data&&x.data.status==='Entwurf'&&!x.data.protected)){if(x.data.parameterId!==settings.data()?.activeParameters||x.data.priceId!==settings.data()?.activePrice){if(!admin())throw conflict();}}const snaps=await Promise.all(changes.map(x=>t.get(ref(x.kind,x.id))));const projectChanges=changes.filter(x=>x.kind==='projects'&&x.data),numbers=await Promise.all(projectChanges.map(x=>t.get(ref('numbers',x.data.numberKey))));changes.forEach((x,i)=>{const cur=snaps[i];if((cur.exists()?cur.data().revision:0)!==(x.old?.revision||0))throw conflict();});numbers.forEach((n,i)=>{if(n.exists()&&n.data().projectId!==projectChanges[i].id)throw Error('Diese Projektnummer wurde inzwischen vergeben. Bitte eine andere Nummer wählen.');});projectChanges.forEach((x,i)=>{if(!numbers[i].exists())t.set(ref('numbers',x.data.numberKey),{projectId:x.id,createdBy:uid(),createdAt:api.serverTimestamp()});});changes.forEach(x=>{if(x.data)t.set(ref(x.kind,x.id),{...x.data,...meta(x.old)});else t.delete(ref(x.kind,x.id));});});for(const x of changes){if(x.data){const saved=await api.getDocFromServer(ref(x.kind,x.id));headers.set(x.kind+'/'+x.id,{...saved.data(),id:x.id});}else headers.delete(x.kind+'/'+x.id);}}
for(const x of changes.filter(x=>!x.data&&['projects','matrices'].includes(x.kind))){try{await removeEntityBlobs(x.kind,x.id);}catch(e){console.error('KalkPro deletion cleanup',e);root.KPStorage.deletionWarning='Der Eintrag wurde gelöscht. Die Bereinigung zugehöriger Cloud-Dokumente konnte nicht vollständig abgeschlossen werden. Bitte den Administrator informieren.';}}
baseline=M.clone(next);return M.clone(next);
}catch(e){throw error(e);}finally{writing=false;}}
async function backup(){needAdmin();const s=await read();if(!s)throw Error('Noch keine Cloud-Daten vorhanden.');return {...s,cloudRuntime:await runtimeData(),cloudBackup:{version:'0.2.0',createdAt:new Date().toISOString(),createdBy:session.email}};}
async function restore(input,bootstrapRuntime){needAdmin();if(writing)throw Error('Ein Speichervorgang läuft bereits.');writing=true;const oldGeneration=generation,oldRevision=controlRevision;try{const rt=bootstrapRuntime||input.cloudRuntime||runtime;if(!rt?.source?.sheets||!rt.source.sourceSha256)throw Error('Geschützte Ausgangsdaten fehlen. Bitte das private Ausgangsdatenpaket importieren.');const s=M.clone(input);delete s.cloudRuntime;delete s.cloudBackup;M.validateState(s,rt.source.sourceSha256);
// Preserve custom/legacy project bases as separate immutable versions during admin migration.
for(const p of s.projects){for(const target of [p,p.actual?.plannedProject].filter(Boolean)){if(target.parameters){const found=s.parameterVersions.find(v=>v.id===target.parameterVersion);if(!found||!M.equal(found.overrides||{},target.parameters)){const id='migration-'+(await M.hash(M.canonical(target.parameters))).slice(0,32);if(!s.parameterVersions.some(v=>v.id===id))s.parameterVersions.push({id,date:target.modified||new Date().toISOString(),user:session.email,overrides:M.clone(target.parameters)});target.parameterVersion=id;}}if(target.priceOverrides){const found=s.priceVersions.find(v=>v.id===target.priceVersion);if(!found||!M.equal(found.overrides||{},target.priceOverrides)||!M.equal(found.pdsCatalog||null,target.pdsCatalog||null)){const id='migration-'+(await M.hash(M.canonical([target.priceOverrides,target.pdsCatalog||null]))).slice(0,32);if(!s.priceVersions.some(v=>v.id===id))s.priceVersions.push({id,name:target.priceName||'Migrierter Projektpreisstand',date:target.modified||new Date().toISOString(),user:session.email,overrides:M.clone(target.priceOverrides),pdsCatalog:M.clone(target.pdsCatalog||null)});target.priceVersion=id;}}}}
generation=crypto.randomUUID();headers.clear();blobCache.clear();const g=generation;
await api.setDoc(ref('runtime','main'),{blob:await stage('runtime','main',rt),...meta()});for(const [kind,key]of [['prices','priceVersions'],['parameters','parameterVersions']])for(const v of s[key])await api.setDoc(ref(kind,v.id),{blob:await stage(kind,v.id,v),...meta()});
for(const p of s.projects){const x=M.splitProject(p),plan=await stage('plan',p.id,x.plan),actual=await stage('actual',p.id,x.actual),m=await stage('meta',p.id,x.meta);let planned=null,pp='',pr='';if(p.actual){const bp=p.actual.plannedProject||p;planned=await stage('plan',p.id,M.splitProject(bp).plan);pp=bp.parameterVersion;pr=bp.priceVersion;}const numberKey=await M.hash(M.numberKey(p.number));await api.setDoc(ref('numbers',numberKey),{projectId:p.id,createdBy:uid(),createdAt:api.serverTimestamp()});await api.setDoc(ref('projects',p.id),{plan,actual,meta:m,planned,plannedParameterId:pp,plannedPriceId:pr,parameterId:x.parameterId,priceId:x.priceId,status:x.status,protected:x.protected,locked:x.locked,actualClosed:x.actual?.status==='Abgeschlossen',numberKey,...meta()});}
for(const [id,m]of [['current',s.matrixCurrent],...(s.matrixHistory||[]).map(m=>[m.id,m])])if(m)await api.setDoc(ref('matrices',id),{blob:await stage('matrices',id,m),...meta()});await api.setDoc(ref('settings','main'),{activePrice:s.activePrice,activeParameters:s.activeParameters,...meta()});await api.setDoc(ref('counters','projects'),{value:s.lastNumber,updatedAt:api.serverTimestamp(),updatedBy:uid()});
await api.runTransaction(db,async t=>{const c=await t.get(control());if((c.exists()?c.data().revision:0)!==oldRevision||(c.exists()?c.data().generation:null)!==(oldGeneration||null))throw conflict();t.set(control(),{generation:g,revision:oldRevision+1,updatedAt:api.serverTimestamp(),updatedBy:uid(),schema:1});});generation=g;controlRevision=oldRevision+1;runtime=rt;baseline=null;return await read();
}catch(e){generation=oldGeneration;controlRevision=oldRevision;baseline=null;throw error(e);}finally{writing=false;}}
root.KPStorage={init,read,write,reserveNumber,runtimeData,backup,restore,clear,error};
})(globalThis);
